CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(edge_detector VERSION 1.3 LANGUAGES CXX)
ENABLE_LANGUAGE(CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -O0 -Wall")
set(CMAKE_CXX_FLAGS_RELEASE "-g -O3 -Wall")
enable_testing()

FIND_PACKAGE(OpenCV REQUIRED )
LINK_LIBRARIES(${OpenCV_LIBS})
include_directories ("${OpenCV_INCLUDE_DIRS}")

add_executable(edge_detector edge_detector.cpp common_code.hpp common_code.cpp)
add_executable(edge_detector_test_common_code test_common_code.cpp common_code.cpp common_code.hpp)
set_target_properties(edge_detector_test_common_code PROPERTIES OUTPUT_NAME "test_common_code")

add_test(NAME TestFSIVComputeDerivate COMMAND test_common_code fsiv_compute_derivate)
add_test(NAME TestFSIVComputeGradientMagnitude COMMAND test_common_code fsiv_compute_gradient_magnitude)
add_test(NAME TestFSIVComputeGradientHistogram COMMAND test_common_code fsiv_compute_gradient_histogram)
add_test(NAME TestFSIVComputeHistogramPercentile COMMAND test_common_code fsiv_compute_histogram_percentile)
add_test(NAME TestFSIVHistogramIdxToValue COMMAND test_common_code fsiv_histogram_idx_to_value)
add_test(NAME TestFSIVThiningEdgeMap COMMAND test_common_code fsiv_thinning_edge_map)
add_test(NAME TestFSIVPercentileEdgeDetector COMMAND test_common_code fsiv_percentile_edge_detector)
add_test(NAME TestFSIVOtsuEdgeDetector COMMAND test_common_code fsiv_otsu_edge_detector)
add_test(NAME TestFSIVCannyEdgeDetector COMMAND test_common_code fsiv_canny_edge_detector)
add_test(NAME TestFSIVComputeGroundTruthImage COMMAND test_common_code fsiv_compute_ground_truth_image)
add_test(NAME TestFSIVComputeEdgeDetectorConfusionMatrix COMMAND test_common_code fsiv_compute_edge_detector_confusion_matrix)
add_test(NAME TestFSIVComputeSensitivity COMMAND test_common_code fsiv_compute_sensitivity)
add_test(NAME TestFSIVComputePrecision COMMAND test_common_code fsiv_compute_precision)
add_test(NAME TestFSIVComputeF1Score COMMAND test_common_code fsiv_compute_F1_score)
