CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(sharpening VERSION 1.12.1 LANGUAGES CXX)
ENABLE_LANGUAGE(CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -O0 -Wall")
set(CMAKE_CXX_FLAGS_RELEASE "-g -O3 -Wall")
enable_testing()

FIND_PACKAGE(OpenCV REQUIRED)
LINK_LIBRARIES(${OpenCV_LIBS})
include_directories("${OpenCV_INCLUDE_DIRS}")

add_executable(sharpen sharpen.cpp common_code.cpp common_code.hpp)
add_executable(sharpening_test_common_code test_common_code.cpp common_code.cpp common_code.hpp)
set_target_properties(sharpening_test_common_code PROPERTIES OUTPUT_NAME "test_common_code")

add_test(NAME TestFSIVCreateGaussianFilter COMMAND test_common_code fsiv_create_gaussian_filter)
add_test(NAME TestFSIVCreateLap4Filter COMMAND test_common_code fsiv_create_lap4_filter)
add_test(NAME TestFSIVCreateLap8Filter COMMAND test_common_code fsiv_create_lap8_filter)
add_test(NAME TestFSIVFillExpansion COMMAND test_common_code fsiv_fill_expansion)
add_test(NAME TestFSIVCircularExpansion COMMAND test_common_code fsiv_circular_expansion)
add_test(NAME TestFSIVCreateDoGFilter COMMAND test_common_code fsiv_create_dog_filter)
add_test(NAME TestFSIVCreateSharpeningFilter COMMAND test_common_code fsiv_create_sharpening_filter)
add_test(NAME TestFSIVImageSharpening COMMAND test_common_code fsiv_image_sharpening)