CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(usm_enhance VERSION 1.10 LANGUAGES CXX)
ENABLE_LANGUAGE(CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS_DEBUG "-ggdb3 -O0 -Wall")
set(CMAKE_CXX_FLAGS_RELEASE "-g -O3 -Wall")
enable_testing()

FIND_PACKAGE(OpenCV REQUIRED)
LINK_LIBRARIES(${OpenCV_LIBS})
include_directories("${OpenCV_INCLUDE_DIRS}")

add_executable(usm_enhance usm_enhance.cpp common_code.cpp common_code.hpp)
add_executable(usm_enhance_test_common_code test_common_code.cpp common_code.cpp common_code.hpp)
set_target_properties(usm_enhance_test_common_code PROPERTIES OUTPUT_NAME "test_common_code")

add_test(NAME TestFSIVCreateBoxFilter COMMAND test_common_code fsiv_create_box_filter)
add_test(NAME TestFSIVCreateGaussianFilter COMMAND test_common_code fsiv_create_gaussian_filter)
add_test(NAME TestFSIVFillExpansion COMMAND test_common_code fsiv_fill_expansion)
add_test(NAME TestFSIVCircularExpansion COMMAND test_common_code fsiv_circular_expansion)
add_test(NAME TestFSIVFilter2D COMMAND test_common_code fsiv_filter2D)
add_test(NAME TestFSIVSoftCombineImages COMMAND test_common_code fsiv_soft_combine_images)
add_test(NAME TestFSIVUSMEnhanceNoCircular COMMAND test_common_code fsiv_usm_enhance_no_circular)
add_test(NAME TestFSIVUSMEnhanceCircular COMMAND test_common_code fsiv_usm_enhance_circular)
